---
title: Code
slug: code/
output:
  html_document:
    keep_md: yes
---



> **Disclaimer**: This code is provided as is, without warranty of any kind. Use at your own risk. No support or maintenance is provided. The author is not liable for any damages arising from its use.
 

**Sampling from the gamcon distribution of Type 1**. Samples from the GamCon distribution of Type 1 of Damsleth (1975) employing the algorithm of Devroye (2012). This distribution is conjugate for the shape parameter of the Gamma distribution with known scale. Programming language is Matlab/Octave. [Download](storage/code/GamConType1.zip).

**Sampling a from non-absorving Squared Bessel Bridge**. Simulates an exact path of a non-absorving Square Bessel Bridge at a predefined time grid. Includes an implementation of the first algorithm of Devroye (2002) for Bessel random variables. Can also be employed to sample from other bridges for processes with known transformations to the Squared Bessel process. Programming language is Matlab/Octave. [Download](storage/code/sampleSQBbridge.zip)

