---
slug: research/
output: 
  html_document: 
    keep_md: yes
---

## Working Papers

Amengual, D., Puig-Codina, L. (2026) A Bayesian Analysis of the Cox-Ingersoll-Ross Model. *Coming Soon*.

Ganics, G., Puig-Codina, L. (2025) Simple Tests for the Correct Specification of Conditional Predictive Densities. *Bank of Spain Working Paper Series, 2535*. [Link](https://www.bde.es/f/webbe/SES/Secciones/Publicaciones/PublicacionesSeriadas/DocumentosTrabajo/25/Files/dt2535e.pdf).

\

## Publications

Puig-Codina, L., Pinilla, J., Puig-Junoy, J. (2021). The impact of taxing sugar-sweetened beverages on cola purchasing in Catalonia: an approach to causal inference with time series cross-sectional data. *The European Journal of Health Economics, 22*(22), 155-168. [Link](https://link.springer.com/article/10.1007/s10198-020-01246-0).

Puig-Junoy, J., Pascual-Argente, N., Puig-Codina, L., Planellas, L., & Solozabal, M. (2018). Cost-utility analysis of second-generation direct-acting antivirals for hepatitis C: a systematic review. *Expert Review of Gastroenterology & Hepatology, 12*(12), 1251-1263. [Link](https://www.tandfonline.com/doi/abs/10.1080/17474124.2018.1540929).

\

## Other

Puig-Codina, L. (2017). Determinacy in a Canonical New Keynesian model under a Money Growth Rule.
[Link](/documents/Determinacy_in_a_Canonical_New_Keynesian_Model_under_a_Money_Growth_Rule.pdf). [Presentation](/documents/IV_Navarra_Macro_Workshop_post_Debortoli.pdf).
